# version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env
    networks:
      - parking-network

  web:
    build: .
    command: gunicorn parking_system.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/Parking_Service/parking_system/static
    expose:
      - "8000"
    depends_on:
      - db
    environment:
      DEBUG: 'false'
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: db
      DB_PORT: "5432"
    networks:
      - parking-network


  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/Parking_Service/parking_system/static
    ports:
      - "8000:80"
    depends_on:
      - web
    networks:
      - parking-network


volumes:
  postgres_data:
  static_volume:

networks:
  parking-network:
